version: '3'

services:
  db:
    image: postgres
    env_file: ./config_files/env-dev

  api:
    build: ./ong_api
    env_file: ./config_files/env-dev
    ports:
      - "8000:8000"
    volumes:
      - ./ong_api/:/code/
      - ./logs/uwsgi/:/logs/uwsgi/
      - ./config_files/uwsgi-dev.ini:/tmp/uwsgi-dev.ini
    links:
      - db

  # webapp:
  #   build: ./ong-webapp
  #   env_file: ./config_files/env-dev
  #   ports:
  #     - 4200:4200
  #     - 49152:49152
  #   volumes:
  #     - ./ong-webapp/:/code/
  #     - ./logs/uwsgi/:/logs/uwsgi/
  #   links:
  #     - api
