version: '3'

services:
  db:
    image: postgres
    env_file: ./config_files/env-dev

  api:
    build: ./ong_api
    env_file: ./config_files/env-dev
    ports:
      - "8000:8000"
    volumes:
      - ./ong_api/:/code/
      - ./logs/uwsgi/:/logs/uwsgi/
      - ./config_files/uwsgi-dev.ini:/tmp/uwsgi-dev.ini
    links:
      - db
