version: '2'
networks: 
  frontend:
  backend:

services:
  db:
    restart: always
    image: postgres
    networks: 
      - backend

  api:
    restart: always
    build: ong_api/
    volumes:
      - ./ong_api/:/code
    ports:
      - "80:80"
    depends_on:
      - db
    networks: 
      - frontend
      - backend
    environment: 
      - DJANGO_SETTINGS_MODULE=ong.dev_settings