# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-28 00:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('cpf', models.CharField(max_length=16)),
                ('rg', models.CharField(max_length=12)),
                ('birth_date', models.DateField()),
                ('genre', models.CharField(choices=[('1', 'Feminino'), ('2', 'Masculino')], max_length=2)),
                ('cep', models.CharField(max_length=10)),
                ('logradouro', models.CharField(max_length=255)),
                ('complemento', models.CharField(blank=True, max_length=128, null=True)),
                ('bairro', models.CharField(max_length=128)),
                ('localidade', models.CharField(max_length=128)),
                ('uf', models.CharField(max_length=8)),
                ('guardians', models.ManyToManyField(blank=True, related_name='protecteds', to=settings.AUTH_USER_MODEL)),
                ('phones', models.ManyToManyField(related_name='phones', to='core.Phone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
        ),
    ]
