# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-26 23:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='guardians',
            field=models.ManyToManyField(blank=True, null=True, related_name='protecteds', to=settings.AUTH_USER_MODEL),
        ),
    ]
