# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-12 02:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phone',
            options={'ordering': ['company__name', 'number']},
        ),
    ]
